'use client';

import { FormEvent, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BadgeCheck, Banknote, Building2, Check, ChevronLeft, Clock3, ExternalLink, FileCheck2, Home, MapPin, MessageCircle, Search, ShieldCheck, Sparkles, Star, TrendingUp, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Textarea } from '@/components/ui/textarea';
import type { GooglePlaceResult, GooglePlaceSearchResponse } from '@/lib/google-place-types';
import { SAHAAN_WHATSAPP_DISPLAY, sahaanWhatsAppUrl } from '@/lib/contact';

const skills = ['Manicure', 'Gel polish', 'Gel manicure', 'Nail extensions', 'Custom nail art', 'Pedicure', 'Bridal nails'];

export default function PartnersPage() {
  const [step, setStep] = useState(1);
  const [submitted, setSubmitted] = useState(false);
  const [bookings, setBookings] = useState(12);
  const [averagePrice, setAveragePrice] = useState(1499);
  const [selectedSkills, setSelectedSkills] = useState<string[]>(['Gel polish']);
  const [form, setForm] = useState({ name: '', businessName: '', phone: '', email: '', city: 'Hyderabad', area: '', experience: '', instagram: '', travel: '8', portfolio: '', availability: 'Weekdays and weekends' });
  const [lookupPin, setLookupPin] = useState('');
  const [lookupName, setLookupName] = useState('');
  const [lookupPlaces, setLookupPlaces] = useState<GooglePlaceResult[]>([]);
  const [lookupLoading, setLookupLoading] = useState(false);
  const [lookupError, setLookupError] = useState('');
  const [selectedListing, setSelectedListing] = useState<GooglePlaceResult | null>(null);
  const monthlyGross = bookings * averagePrice;
  const commission = Math.round(monthlyGross * .18);
  const partnerEarnings = monthlyGross - commission;
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const canContinue = useMemo(() => step === 1 ? Boolean(form.name && form.phone && form.city && form.area) : step === 2 ? Boolean(form.experience && selectedSkills.length) : true, [form, selectedSkills, step]);

  async function findGoogleProfile(event: FormEvent) {
    event.preventDefault();
    if (!/^\d{6}$/.test(lookupPin)) {
      setLookupError('Enter a valid 6-digit Hyderabad PIN code.');
      return;
    }
    setLookupLoading(true);
    setLookupError('');
    try {
      const response = await fetch(`/api/google-professionals?pin=${encodeURIComponent(lookupPin)}&service=Beauty%20salon&name=${encodeURIComponent(lookupName)}`, { cache: 'no-store' });
      const body = await response.json() as GooglePlaceSearchResponse & { error?: string };
      if (!response.ok) throw new Error(body.error || 'Unable to search Google Maps right now.');
      setLookupPlaces(body.places.slice(0, 6));
    } catch (reason) {
      setLookupPlaces([]);
      setLookupError(reason instanceof Error ? reason.message : 'Unable to search Google Maps right now.');
    } finally {
      setLookupLoading(false);
    }
  }

  function useGoogleListing(place: GooglePlaceResult) {
    setSelectedListing(place);
    setForm((current) => ({ ...current, businessName: place.name, area: place.address, city: 'Hyderabad' }));
    document.getElementById('application')?.scrollIntoView({ behavior: 'smooth' });
  }

  function submit(event: FormEvent) {
    event.preventDefault();
    const application = `Hi Sahaan! I would like to apply as a founding beauty professional in Hyderabad.\n\nName: ${form.name}\nBusiness / salon name: ${form.businessName || 'Independent professional'}\nPhone: ${form.phone}\nEmail: ${form.email || '—'}\nCity & service area: ${form.city}, ${form.area}\nExperience: ${form.experience}\nSkills: ${selectedSkills.join(', ')}\nInstagram: ${form.instagram || '—'}\nTravel radius: ${form.travel} km\nAvailability: ${form.availability}\nPortfolio: ${form.portfolio || 'Will share on request'}\nGoogle Maps listing: ${selectedListing?.mapsUrl || 'Not selected'}\nGoogle rating at application: ${selectedListing?.rating || 'Not available'} (${selectedListing?.reviewCount || 0} reviews)\n\nI agree to Sahaan's hygiene, service and customer-care standards.`;
    setSubmitted(true);
    window.open(sahaanWhatsAppUrl(application), '_blank', 'noopener,noreferrer');
  }

  return <main className="partner-page">
    <header className="market-header inner-header professional-header"><a className="market-brand" href="/partners"><span className="market-monogram">S</span><span><strong>SAHAAN</strong><small>PROFESSIONAL NETWORK</small></span></a><nav className="desktop-nav"><a href="#benefits">Why Sahaan</a><a href="#earnings">Earnings</a><a href="#application">Application</a></nav><div className="header-actions"><a className="profile-back" href="/"><ArrowLeft /> Customer website</a><a className="signin-link" href="#application">Apply now</a></div></header>
    <section className="partner-hero"><div className="partner-copy"><a href="/" className="back-link"><ArrowLeft /> Back to Sahaan</a><div className="founding-badge"><Sparkles /> Hyderabad founding professional programme</div><h1>Grow your craft.<br /><em>Let’s build the client base.</em></h1><p>Sahaan is preparing a managed home-service pilot in Kondapur–Gachibowli and Jubilee Hills–Banjara Hills. Apply now for review; activation and customer requests depend on coverage, checks and demand.</p><div className="partner-actions"><Button render={<a href="#google-profile" />}>Find your Google profile <ArrowRight /></Button><a href="#earnings">See earning potential</a></div><div className="partner-proof"><div><strong>0%</strong><span>commission on your first 10 completed bookings</span></div><div><strong>Clear terms</strong><span>confirmed before your first job</span></div><div><strong>You choose</strong><span>areas, services and availability</span></div></div></div><div className="partner-visual"><div className="partner-quote"><Star fill="currentColor" /><p>“Sahaan helps talented Hyderabad professionals be discovered for the quality of their work.”</p><span>THE FOUNDING PROFESSIONAL PROMISE</span></div></div></section>

    <section className="partner-benefits" id="benefits"><p className="eyebrow">Built for independent professionals</p><h2>Your talent. Your schedule.<br />A business that grows with you.</h2><div className="benefit-grid"><article><div><TrendingUp /></div><strong>Relevant enquiries</strong><p>As the pilot grows, Sahaan will review customer requests against your skills and service area.</p></article><article><div><Clock3 /></div><strong>Work on your terms</strong><p>Choose your service areas, working days, appointment times and minimum prices.</p></article><article><div><Banknote /></div><strong>Price clarity</strong><p>Confirm the service value, commission and payment arrangement before accepting a job.</p></article><article><div><ShieldCheck /></div><strong>Founder-led support</strong><p>During the pilot, Sahaan will coordinate requests and discuss issues directly with you.</p></article></div></section>

    <section className="partner-cta"><div><p className="eyebrow">For beauty professionals</p><h2>Your talent deserves<br /><em>the right clients.</em></h2><p>Apply for a Sahaan profile and choose when and where you can work. We will contact shortlisted applicants as the two pilot areas are prepared; applying does not guarantee bookings.</p><Button render={<a href="#application" />}>Apply as a founding professional <ArrowRight /></Button></div><div className="partner-cta-stats"><span><strong>0%</strong><small>commission on your first 10 completed bookings</small></span><span><strong>18%</strong><small>standard commission after launch offer</small></span><span><strong>Before launch</strong><small>payment terms agreed in writing</small></span></div></section>

    <section className="earnings-section" id="earnings"><div className="earnings-copy"><p className="eyebrow">Know your numbers</p><h2>A clear commission,<br />never a surprise.</h2><p>After your first 10 commission-free completed bookings, Sahaan’s proposed standard platform commission is 18% on completed appointments. The payment method and final terms are agreed before activation.</p><ul><li><Check /> No joining or profile-listing fee</li><li><Check /> No commission on cancelled bookings</li><li><Check /> Tips remain 100% yours</li><li><Check /> Written job and payment terms before the first booking</li></ul></div><div className="calculator-card"><div className="calculator-head"><span>Monthly earnings estimator</span><TrendingUp /></div><label><span>Bookings per month <strong>{bookings}</strong></span><input type="range" min="4" max="40" step="2" value={bookings} onChange={(e) => setBookings(Number(e.target.value))} /></label><label><span>Average service price</span><select value={averagePrice} onChange={(e) => setAveragePrice(Number(e.target.value))}><option value="999">₹999</option><option value="1499">₹1,499</option><option value="1999">₹1,999</option><option value="2999">₹2,999</option></select></label><div className="earnings-breakdown"><span>Customer booking value <strong>₹{monthlyGross.toLocaleString('en-IN')}</strong></span><span>Sahaan commission · 18% <strong>− ₹{commission.toLocaleString('en-IN')}</strong></span><div><span>Your estimated earnings</span><strong>₹{partnerEarnings.toLocaleString('en-IN')}</strong></div></div><small>Illustrative estimate after the first 10 completed bookings; not a promise of bookings or earnings. Before taxes and your own material or travel costs.</small></div></section>

    <section className="google-profile-section" id="google-profile"><div className="google-profile-copy"><p className="eyebrow">Optional first step</p><h2>Find your existing<br />Google Business Profile.</h2><p>Search by Hyderabad PIN code and business name. Selecting a listing pre-fills your salon name and address, while Sahaan verification remains a separate process.</p><div className="google-profile-warning"><ShieldCheck /><span><b>Important:</b> A Google listing, rating or review count does not automatically approve a Sahaan profile.</span></div></div><div className="google-profile-tool"><form onSubmit={findGoogleProfile}><label><span className="field-title">Hyderabad PIN code <b>Required</b></span><Input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={lookupPin} onChange={(event) => setLookupPin(event.target.value.replace(/\D/g, '').slice(0, 6))} placeholder="e.g. 500081" /></label><label><span className="field-title">Salon or business name <i>Optional</i></span><Input value={lookupName} onChange={(event) => setLookupName(event.target.value)} placeholder="e.g. Your salon name" /></label><Button type="submit" disabled={lookupLoading}><Search /> {lookupLoading ? 'Searching…' : 'Find Google profile'}</Button></form>{lookupError && <div className="lookup-error"><ShieldCheck /><span>{lookupError}</span></div>}{lookupPlaces.length > 0 && <div className="lookup-results"><div className="lookup-results-head"><strong>Possible matches</strong><span className="google-maps-attribution" translate="no">Google Maps</span></div>{lookupPlaces.map((place) => <article key={place.placeId} className={selectedListing?.placeId === place.placeId ? 'selected' : ''}><div><Building2 /><span><strong>{place.name}</strong><small>{place.address}</small><em><Star fill="currentColor" /> {place.rating?.toFixed(1) || 'New'} · {place.reviewCount.toLocaleString('en-IN')} reviews</em></span></div><div><a href={place.mapsUrl} target="_blank" rel="noreferrer" aria-label={`View ${place.name} on Google Maps`}><ExternalLink /></a><Button type="button" onClick={() => useGoogleListing(place)}>{selectedListing?.placeId === place.placeId ? 'Selected' : 'Use this profile'}</Button></div></article>)}<small>Google Maps ratings and review counts are user-generated and may change.</small></div>}</div></section>

    <section className="application-section" id="application"><div className="application-intro"><p className="eyebrow">Apply in under 5 minutes</p><h2>Let’s build your<br />Sahaan profile.</h2><p>We review every application personally. Strong portfolios and reliable service standards matter more than follower count.</p><div className="review-steps"><span><BadgeCheck /> Identity and contact check</span><span><FileCheck2 /> Portfolio and experience review</span><span><MessageCircle /> Short WhatsApp interview</span><span><Sparkles /> Profile activation</span></div><a className="whatsapp-inline-link" href={sahaanWhatsAppUrl('Hi Sahaan! I have a question about joining as a beauty professional.')} target="_blank" rel="noopener noreferrer"><MessageCircle /> Questions? WhatsApp {SAHAAN_WHATSAPP_DISPLAY}</a></div>
      <div className="application-card">{submitted ? <div className="application-success"><div><Check /></div><p className="eyebrow">Application prepared</p><h3>Thank you, {form.name.split(' ')[0] || 'professional'}.</h3><p>Your application has been prepared in WhatsApp. Send that message to begin the Sahaan review process.</p><Button onClick={() => setSubmitted(false)}>Review application</Button></div> : <form onSubmit={submit}>
        <div className="form-progress"><div><span>Step {step} of 3</span><strong>{step === 1 ? 'About you' : step === 2 ? 'Your expertise' : 'Service preferences'}</strong></div><div className="progress-track"><span style={{ width: `${step * 33.333}%` }} /></div></div>
        {step === 1 && <div className="form-step"><p className="form-instruction">Complete every field marked <b>Required</b>. Use the same details you will provide during verification.</p>{selectedListing && <div className="selected-google-profile"><Building2 /><span><b>Google profile selected</b>{selectedListing.name} · {selectedListing.rating?.toFixed(1) || 'New'} rating · {selectedListing.reviewCount.toLocaleString('en-IN')} reviews</span><a href={selectedListing.mapsUrl} target="_blank" rel="noreferrer"><ExternalLink /></a></div>}<div className="form-two"><label><span className="field-title">Full legal name <b>Required</b></span><Input required value={form.name} onChange={(e) => update('name', e.target.value)} placeholder="Exactly as shown on your ID" /></label><label><span className="field-title">WhatsApp mobile number <b>Required</b></span><Input required type="tel" value={form.phone} onChange={(e) => update('phone', e.target.value)} placeholder="10-digit mobile number" /></label></div><label><span className="field-title">Salon or business name <i>Optional</i></span><Input value={form.businessName} onChange={(e) => update('businessName', e.target.value)} placeholder="Leave blank if you work independently" /></label><label><span className="field-title">Email address <i>Optional</i></span><Input type="email" value={form.email} onChange={(e) => update('email', e.target.value)} placeholder="you@example.com" /></label><div className="form-two"><label><span className="field-title">Launch city <b>Required</b></span><select required value={form.city} onChange={(e) => update('city', e.target.value)}><option>Hyderabad</option><option>Secunderabad</option><option>Greater Hyderabad</option></select></label><label><span className="field-title">Primary service area <b>Required</b></span><Input required value={form.area} onChange={(e) => update('area', e.target.value)} placeholder="Neighbourhood and Hyderabad PIN code" /><small>Where you mainly accept clients. Example: Jubilee Hills, Hyderabad 500033.</small></label></div><div className="privacy-note"><ShieldCheck /> Your contact and location details are used only to review and manage your professional application.</div></div>}
        {step === 2 && <div className="form-step"><label><span className="field-title">Professional experience <b>Required</b></span><select required value={form.experience} onChange={(e) => update('experience', e.target.value)}><option value="">Select your experience</option><option>Less than 1 year</option><option>1–2 years</option><option>3–5 years</option><option>More than 5 years</option></select></label><fieldset><legend>Services you confidently offer <b>Choose at least one</b></legend><div className="skills-grid">{skills.map((skill) => <label className={selectedSkills.includes(skill) ? 'checked' : ''} key={skill}><Checkbox checked={selectedSkills.includes(skill)} onCheckedChange={(checked) => setSelectedSkills((current) => checked ? [...current, skill] : current.filter((item) => item !== skill))} />{skill}</label>)}</div></fieldset><label><span className="field-title">Instagram or portfolio link <i>Optional</i></span><Input value={form.instagram} onChange={(e) => update('instagram', e.target.value)} placeholder="instagram.com/yourwork" /><small>Add a public link where we can review your work.</small></label><label><span className="field-title">Professional background <i>Optional</i></span><Textarea value={form.portfolio} onChange={(e) => update('portfolio', e.target.value)} placeholder="Training, signature style, certifications or proudest work…" /></label></div>}
        {step === 3 && <div className="form-step"><label><span className="field-title">Maximum travel radius <b>Required</b></span><select required value={form.travel} onChange={(e) => update('travel', e.target.value)}><option value="5">Up to 5 km</option><option value="8">Up to 8 km</option><option value="12">Up to 12 km</option><option value="20">Up to 20 km</option></select><small>The maximum distance you can reliably travel for home appointments.</small></label><label><span className="field-title">Typical availability <b>Required</b></span><select required value={form.availability} onChange={(e) => update('availability', e.target.value)}><option>Weekdays and weekends</option><option>Weekdays only</option><option>Weekends only</option><option>Evenings only</option><option>Flexible / changes weekly</option></select></label><div className="standards-card"><strong>The Sahaan professional promise</strong><p>By applying, you confirm that you will:</p><ul><li><Check /> Use sanitised tools and safe products</li><li><Check /> Arrive professionally and on time</li><li><Check /> Honour confirmed prices and services</li><li><Check /> Treat every client and home with respect</li></ul></div><label className="consent-row"><Checkbox required /> <span><b>Required:</b> I agree to follow Sahaan’s service, hygiene and customer-care standards. I understand approval is subject to verification.</span></label></div>}
        <div className="form-controls">{step > 1 ? <Button type="button" variant="outline" onClick={() => setStep((current) => current - 1)}><ChevronLeft /> Back</Button> : <span />}{step < 3 ? <Button type="button" disabled={!canContinue} onClick={() => setStep((current) => current + 1)}>Continue <ArrowRight /></Button> : <Button type="submit"><MessageCircle /> Submit through WhatsApp</Button>}</div>
      </form>}</div>
    </section>
    <section className="partner-faq"><p className="eyebrow">Before you apply</p><h2>Good to know</h2><div><details><summary>Do I need my own salon?<span>+</span></summary><p>No. Sahaan is designed for skilled independent professionals providing services at customers’ homes. You need a clean professional kit and reliable transport.</p></details><details><summary>How does the commission work?<span>+</span></summary><p>Your first 10 completed bookings are commission-free. After that, Sahaan’s proposed standard commission is 18% of the completed service value. Final terms are agreed before activation.</p></details><details><summary>When will I receive payment?<span>+</span></summary><p>The payment method, timing and booking statement will be agreed in writing before your first job. No payment arrangement is active simply because you submit an application.</p></details><details><summary>What documents will be required?<span>+</span></summary><p>Identity, address and bank-account verification will be requested only after the initial application passes portfolio review. Never send sensitive documents through an unverified contact.</p></details></div></section>
    <div className="mobile-nav"><a href="/"><Home /><span>Home</span></a><a href="/professionals"><Search /><span>Explore</span></a><a className="current" href="/partners"><Users /><span>Join</span></a></div>
  </main>;
}
